apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: check-ip
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/network-interfaces: '[{"network":"thps-checkmk-vpc","subnetwork":"thps-checkmk-subnet","tags":["check-nat-ip"]}]'
        run.googleapis.com/vpc-access-egress: all-traffic
    spec:
      template:
        spec:
          timeoutSeconds: 60
          maxRetries: 0
          serviceAccountName: dd-checkip-runner@th-checkmksandbox-lab-b0a655.iam.gserviceaccount.com
          containers:
          - image: northamerica-northeast1-docker.pkg.dev/th-checkmksandbox-lab-b0a655/thps-checkmk-check-nat-ip/check-ip:latest
            resources:
              limits:
                cpu: "2"
                memory: 512Mi
            volumeMounts:
            - name: var-checks
              mountPath: /var/checks
          volumes:
          - name: var-checks
            csi:
              driver: gcsfuse.run.googleapis.com
              volumeAttributes:
                bucketName: sandbox-check_ip