apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: dd-directory
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/network-interfaces: '[{"network":"thps-checkmk-vpc","subnetwork":"thps-checkmk-subnet","tags":["check-nat-ip"]}]'
        run.googleapis.com/vpc-access-egress: all-traffic  
    spec:
      template:
        spec:
          maxRetries: 0
          timeoutSeconds: 86280
          serviceAccountName: dd-checkip-runner@th-checkmksandbox-lab-b0a655.iam.gserviceaccount.com
          containers:
          - image: northamerica-northeast1-docker.pkg.dev/th-checkmksandbox-lab-b0a655/thps-checkmk-check-nat-ip/dd-directory:latest
            env:
            - name: DD_SITE
              value: datadoghq.com
            - name: DD_TAGS
              value: monitor:natip
            - name: DD_HOSTNAME
              value: una-nat-check
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: dd-thdp-una-api
            resources:
              limits:
                cpu: "2"
                memory: 1Gi
            volumeMounts:
            - name: var-checks
              mountPath: /var/checks
          volumes:
          - name: var-checks
            csi:
              driver: gcsfuse.run.googleapis.com
              volumeAttributes:
                bucketName: sandbox-check_ip